### ISSUE TITLE
How to use subtemplates?

### ISSUE THREAD

**Issue by fulv** [collective/collective.documentgenerator#15]
I've installed the demo profile on a Plone 4.3 site and got things to work.  However, I'm not clear on how to use subtemplates.  The demo profile creates a subtemplate titled "Header" alongside the other items in the `podtemplates` folder.  I see that the "Multiple format template" (`id=test_template_multiple`) has this "Header" subtemplate listed under "Templates to merge" (defined here:  https://github.com/collective/collective.documentgenerator/blob/master/src/collective/documentgenerator/setuphandlers.py#L148).  However, I don't see the "POD context name" `header` being used anywhere in the `modele_general.odt` file.  Am I missing something?  Or how is `header` supposed to be used?

I tried adding an Input field in my odt template with reference `header`, but that just prints out the path to the temporary file (e.g. `/tmp/tmpWHC9Of.odt`), so that is obviously not the right way.

**Comment by sgeulette** [comment]
Hi Fulvio,

I see that header parameter is defined in "Multiple format template" but not used in the odt file.
If you look at the "Collection template" odt file, you will see how to include header (with a "comment"). 
If "Do rendering" parameter is True, the subtemplate is rendered before the main template and included with the following syntax : "do text \n from document(at=header, format='odt')".
If "Do rendering" parameter is False, the subtemplate is rendered during the main template rendering and with the same context. With the following syntax : "do text \n from document(content=header.odt_file.data, format='odt')" if the subtemplate is static or "do text \n from pod(content=header.odt_file.data, format='odt')" if the subtemplate contains appy to render in the same context. 

You can also look at french documentation
http://www.imio.be/support/documentation/tutoriels/collective-documentgenerator

Regards

**Comment by fulv** [comment]
Thanks!

I have started translating your documentation into English, feel free to use it as you see fit:
https://gist.github.com/fulv/bde72273fe1513ee19f386fa2450b3ef

I've found the Collection Template file and how it's done there.  However, I get an error when I try to render it:

```
2017-11-24 17:23:18 ERROR Zope.SiteErrorLog 1511540598.50.979280168965 http://localhost:8080/demo/news/aggregator/document-generation
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module collective.documentgenerator.browser.generation_view, line 46, in __call__
  Module collective.documentgenerator.browser.generation_view, line 62, in generate_and_download_doc
  Module collective.documentgenerator.browser.generation_view, line 87, in _generate_doc
  Module collective.documentgenerator.browser.generation_view, line 126, in _recursive_generate_doc
  Module collective.documentgenerator.browser.generation_view, line 215, in _render_document
  Module appy.pod.renderer, line 433, in run
  Module appy.shared.xml_parser, line 284, in parse
  Module xml.sax.expatreader, line 107, in parse
  Module xml.sax.xmlreader, line 123, in parse
  Module xml.sax.expatreader, line 210, in feed
  Module xml.sax.expatreader, line 307, in end_element
  Module appy.pod.pod_parser, line 341, in endElement
  Module appy.pod.actions, line 144, in execute
  Module appy.pod.actions, line 407, in do
  Module appy.pod.actions, line 161, in evaluateBuffer
  Module appy.pod.actions, line 91, in manageError
EvaluationError: Error while evaluating the expression "document(at=header, format='odt')" defined in the "from" part of a statement. AttributeError: startswith
> /home/fulvio/plone/xxx/buildout-cache/eggs/appy-0.9.8-py2.7.egg/appy/pod/actions.py(91)manageError()
-> raise EvaluationError(originalError, errorMessage)
```

**Comment by fulv** [comment]
Digging a bit deeper... the error comes from `appy/pod/doc_importers.py`:

```
 94     def checkAt(self, at, raiseOnError=True):                                                                                                                                    
 95         '''Check and apply some transform to p_at'''                                                                                                                             
 96         # Resolve relative path                                                                                                                                                  
 97         if at.startswith('./'): at = os.path.join(os.getcwd(), at[2:])                                                                                                           
 98         # Checks that p_at corresponds to an existing file if given                                                                                                              
 99         if raiseOnError and not os.path.isfile(at):                                                                                                                              
100             raise PodError(FILE_NOT_FOUND % at)                                                                                                                                  
101         return at                                                                                                                                                                
```

In line 97, `at` is:

```
(Pdb) at
<SubTemplate at /demo/podtemplates/sub_template>
```

and so it does not have a `startswith` method.  The `checkAt` method seems to expect a file path, not an object.

**Comment by sgeulette** [comment]
Hi Fulvio,
I have corrected the demo template named "Collection template".
Before all subtemplates were pre-rendered.
I forgot to adapt those template after "post rendering" functionality.
Regards

**Comment by fulv** [comment]
Thanks, @sgeulette !
