### ISSUE TITLE
Text not properly wrapping around images in PDF format

### ISSUE THREAD

**Issue by fulv** [collective/collective.documentgenerator#17]
I was wondering if anyone had figured out a solution to this simple problem.  Since a picture is worth 1000 words, here is the problem:

![screenshot 2018-02-15 at 18 05 42](https://user-images.githubusercontent.com/460742/36270006-f374e07c-127a-11e8-8cc1-7c93d3418f70.png)
This is how the default `modele_general.odt` template renders PDF when there is an image in the body text of a page.

On the other hand, this is how the same text with image is rendered in the browser:

![screenshot 2018-02-15 at 18 09 31](https://user-images.githubusercontent.com/460742/36270217-6cee06d6-127b-11e8-9c03-80d627f4304e.png)

I have tried changing the styles in the odt file, with no success.  That is, viewed in LibreOffice, the text wraps correctly, but when used by appy.pod, the resulting PDF view has no wrapping.

This is on a brand new Plone 4 site, Sunburst theme, no special styles, with text and images entered in the content body using TinyMCE.  I have spent hours in LibreOffice, tweaking all the F11 "Styles and Formatting" settings for Frames -> Graphics, and some of those settings result in a change in the PDF output, but some don't.

**Comment by fulv** [comment]
Ok, I found a workaround, after discovering that the PDF generated by appy correctly applies inline CSS style applied to the img tag.

So I created a browser view called `styled_text` in which I parse the `text` field of the context and apply some inline CSS to any `img` tags, and I overrode the `get_value` method of the `ATDemoHelperView`.  In the odt file I use this:

```
do text
from view.render_xhtml('styled_text')
```


It would be nice if `get_value` were able to recognize browser views in addition to AT or DX fields.  If this sounds interesting, I would be happy to create a new issue and submit a PR.

```
from collective.documentgenerator.demo.helper import ATDemoHelperView                                                                                                                                               
from plone.api.content import get_view                                                                                                                                                                              
from plone.api.exc import InvalidParameterError                                                                                                                                                                     
                                                                                                                                                                                                                    
class HelperView(ATDemoHelperView):                                                                                                                                                                                 
                                                                                                                                                                                                                    
    def get_value(self, field_name, default=None, as_utf8=False):                                                                                                                                                   
        try:                                                                                                                                                                                                        
            value = get_view(field_name, self.real_context, self.request)()                                                                                                                                         
            if as_utf8 and isinstance(value, unicode):                                                                                                                                                              
                value = value.encode('utf8')                                                                                                                                                                        
            return value                                                                                                                                                                                            
        except InvalidParameterError:                                                                                                                                                                               
            return super(HelperView, self).get_value(field_name, default, as_utf8)                                                                                                                                  
```

**Comment by gbastien** [comment]
Hi @fulv 

yes if you have a class "image-left" applied to you image, you can add a style named "image-left" in your ODT template that will do the same, it will be applied to rendered images.

I styles names are the same (class in HTML and style in LibreOffice), styles mapping is done automagically.  But you may also define custom styles when calling the xhtml() method, using for example stylesMapping={'para':'Text body'} will apply the "Text Body" default LibreOffice style to every paragraphs.

There is not much documentation about stylesMapping but it is very convenient, for example when you want to apply some default alignment to rendered text or so.

See you,

Gauthier
