### ISSUE TITLE
The documentation on appyframework.org is not available

### ISSUE THREAD

**Issue by holdenhao** [collective/collective.documentgenerator#31]
It may be temporary.  A copy is available from:

[https://web.archive.org/web/20191022054205/http://appyframework.org/](https://web.archive.org/web/20191022054205/http://appyframework.org/)

**Comment by odelaere** [comment]
Hi @holdenhao 

You may want to contact appy.pod's creator and maintainer at this address : info@appyframework.org.

Anyway I will pass the word next time I have a chance to speak with him ;)
