### ISSUE TITLE
update for Plone 5.x?

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.documentgenerator#7]
If this works with Plone 5.0 and/or 5.1, please add the pypi classifier "Framework :: Plone :: 5.0" etc. to setup.py and mention Plone 5.x compatibility in the README.rst - thanks!

**Comment by sgeulette** [comment]
Hi Kim,
The product is now compatible with both Plone 4.3, Plone 5.0 and Plone 5.1 (from 2.0.0 version). 
Regards
